----- 第一个
-- `with xx as ()` 是SQL的语法。
--把MODEL换成TABLE就是标准的SQL，该SQL来自：https://cloud.google.com/bigquery-ml/docs/kmeans-tutorial?hl=zh-cn
CREATE OR REPLACE MODEL
  BQML_TUTORIAL.LONDON_STATION_CLUSTERS OPTIONS(MODEL_TYPE='KMEANS',
    NUM_CLUSTERS=4) AS
WITH
  HS AS (
  SELECT
    H.START_STATION_NAME AS STATION_NAME,
  IF
    (EXTRACT(DAYOFWEEK
      FROM
        H.START_DATE) = 1
      OR EXTRACT(DAYOFWEEK
      FROM
        H.START_DATE) = 7,
      "WEEKEND",
      "WEEKDAY") AS ISWEEKDAY,
    H.DURATION,
    ST_DISTANCE(ST_GEOGPOINT(S.LONGITUDE,
        S.LATITUDE),
      ST_GEOGPOINT(-0.1,
        51.5))/1000 AS DISTANCE_FROM_CITY_CENTER
  FROM
    `BIGQUERY-PUBLIC-DATA.LONDON_BICYCLES.CYCLE_HIRE` AS H
  JOIN
    `BIGQUERY-PUBLIC-DATA.LONDON_BICYCLES.CYCLE_STATIONS` AS S
  ON
    H.START_STATION_ID = S.ID
  WHERE
    H.START_DATE BETWEEN CAST('2015-01-01 00:00:00' AS TIMESTAMP)
    AND CAST('2016-01-01 00:00:00' AS TIMESTAMP) ),
  STATIONSTATS AS (
  SELECT
    STATION_NAME,
    ISWEEKDAY,
    AVG(DURATION) AS DURATION,
    COUNT(DURATION) AS NUM_TRIPS,
    MAX(DISTANCE_FROM_CITY_CENTER) AS DISTANCE_FROM_CITY_CENTER
  FROM
    HS
  GROUP BY
    STATION_NAME, ISWEEKDAY)
SELECT
    * EXCEPT(STATION_NAME, ISWEEKDAY)
FROM
  STATIONSTATS

--- 第二个
---- MODEL换成TABLE就是标准的SQL，来自：https://cloud.google.com/bigquery-ml/docs/create-machine-learning-model?hl=zh-cn#step_two_create_your_model
CREATE MODEL `BQML_TUTORIAL.SAMPLE_MODEL`
OPTIONS(MODEL_TYPE='LOGISTIC_REG') AS
SELECT
    IF(TOTALS.TRANSACTIONS IS NULL, 0, 1) AS LABEL,
    IFNULL(DEVICE.OPERATINGSYSTEM, "") AS OS,
    DEVICE.ISMOBILE AS IS_MOBILE,
    IFNULL(GEONETWORK.COUNTRY, "") AS COUNTRY,
    IFNULL(TOTALS.PAGEVIEWS, 0) AS PAGEVIEWS
FROM
    `BIGQUERY-PUBLIC-DATA.GOOGLE_ANALYTICS_SAMPLE.GA_SESSIONS_*`
WHERE
    _TABLE_SUFFIX BETWEEN '20160801' AND '20170630'
